theme: jekyll-theme-minimal
title: Ayana's homepage
description: Shortcut page to reach my resume and projects.  [View my LinkedIn Page](linkedin.com/in/ayatn)  [View my Resume](docs.google.com/document/d/1iEMYUpNmczf7WG4-v-bN8AK2gV1PBHRHT5JhkI8Hyr8/edit?usp=sharing)
